### ISSUE TITLE
Account username

### ISSUE THREAD

**Issue by eFuller96** [DrenaxCompSci/CSSDImplementation#57]
What's the point of NormalAccount class inheriting from Account, which has member accountUserName, and then create another member userName ?????? just makes 2x usernames associated with normal account.

**Comment by AlexOgden** [comment]
Hahahahahaha

**Comment by eFuller96** [comment]
i'm not being stupid am i @AlexOgden ??!!!!

**Comment by AlexOgden** [comment]
No, somebody is stupid, but it isn't us.

**Comment by eFuller96** [comment]
right i'll close this, 'normal account' won't have username field, but then just leaves DOB and making the whole thing stupid and redundant.
