### ISSUE TITLE
Discuss SetOfStaffAccounts.cs

### ISSUE THREAD

**Issue by eFuller96** [DrenaxCompSci/CSSDImplementation#60]
UML has nothing on this class(no functions/members). I was thinking, wouldn't this also need a 'findAccount' like SetOfAccounts class? or just scrap this class and have just SetOfAccounts.cs

**Comment by AlexOgden** [comment]
Probably should have a findAccount as I did in the other class.

If we have just the one set class, we might need to take a look at implementing a more polymorphic design on Accounts.

**Comment by eFuller96** [comment]
ok, I'll implement findAccounts for sefOfStaffAccounts,.cs
