### ISSUE TITLE
Passes Class

### ISSUE THREAD

**Issue by AlexOgden** [DrenaxCompSci/CSSDImplementation#65]
What a stupid design this one is.

So the Passes (note the plural) contains two dates, start, end, and a string 'type'.

Do this people even have the slightest fucking clue about OOP?

I suggest we delete this, create a 'Pass' interface/abstract class, and have the different passes implement from it, such as 16-25, Student, OAP or something.

**Comment by eFuller96** [comment]
is that in the scope? having diff pass types, like student, oap etc?

**Comment by AlexOgden** [comment]
I think its already there they've just done it weird.
Or we rename it to Pass or Railcard and keep it generic, just doesn't seem to make full sense to me
